publish_to: none
name: pixelart_server
description: An new Dart Frog application
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  dart_frog_web_socket: ^1.0.0
  hive: ^2.2.3
  pixelart_shared:
    path: '../pixelart_shared'
  uuid: ^4.1.0

dev_dependencies:
  lints: ^2.0.0
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
